name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Use the same version as local

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 black isort pytest pytest-cov

    - name: Run Linting (Check for Errors)
      run: flake8 app tests --max-line-length=79

    - name: Auto-Fix Formatting (Optional)
      run: |
        black .
        isort .

    - name: Run Tests with Coverage
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: pytest --cov=app --cov-report=xml

    - name: Upload Coverage Report
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
